bootstrap.servers=${BROKER_LIST}
security.protocol=SASL_PLAINTEXT
sasl.mechanism=PLAIN

sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
  username="consumer2" \
  password="consumer-zjstbaj2~";
  