KafkaServer {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="admin"
   password="admin123"
   user_admin="admin123"
   user_consumer1="consumer-zjstbaj1!"
   user_consumer2="consumer-zjstbaj2~";
};
KafkaClient {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="admin"
   password="admin123";
};
Client {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="admin"
   password="admin123";
};