FROM wurstmeister/kafka:2.12-2.1.0

# 필요한 디렉토리 생성
RUN mkdir -p /var/lib/zookeeper

# 필요한 스크립트 파일 복사
COPY zookeeper/bin/zookeeper-start.sh /usr/bin/zookeeper-start.sh

# 실행 권한 부여
RUN chmod +x /usr/bin/zookeeper-start.sh

# 컨테이너 시작 시 스크립트 실행
CMD ["bash", "-c", "/usr/bin/zookeeper-start.sh"]
