dms_agent.sources = source1
dms_agent.channels = channel1
dms_agent.sinks = sink1

# Kafka source 설정
dms_agent.sources.source1.type = org.apache.flume.source.kafka.KafkaSource
# 소스 배치 크기를 100으로 설정
dms_agent.sources.source1.batchSize = 100
dms_agent.sources.source1.channels = channel1
dms_agent.sources.source1.kafka.bootstrap.servers = localhost:9094
dms_agent.sources.source1.kafka.topics = topic-navilog2-acs-post-json
dms_agent.sources.source1.kafka.consumer.group.id = acs-group
dms_agent.sources.source1.kafka.consumer.security.protocol = SASL_PLAINTEXT
dms_agent.sources.source1.kafka.consumer.sasl.mechanism = PLAIN
dms_agent.sources.source1.kafka.consumer.sasl.jaas.config = org.apache.kafka.common.security.plain.PlainLoginModule required \
    username="consumer1" \
    password="consumer-zjstbaj1!";

# Memory channel 설정
dms_agent.channels.channel1.type = memory
dms_agent.channels.channel1.capacity = 1000
dms_agent.channels.channel1.transactionCapacity = 100

# Logger sink 설정
# dms_agent.sinks.sink1.type = logger
# dms_agent.sinks.sink1.channel = channel1
dms_agent.sinks.sink1.type = com.dms.apps.FlumeCustomSink
dms_agent.sinks.sink1.channel = channel1
